- name: install mysql package playbook
  become: yes
  hosts: node
  ignore_errors: true
  tasks:
    - name: install mysql task
      ansible.builtin.package:
        name: mysql
        state: present
    - name: run  mysql task
      ansible.builtin.service:
        name: sshd
        state: started
        enabled: yes